model:
  name: fc
  in_ch: 5
  out_ch: 64
  layer_num: 3
  feats: ['age', 'height', 'weight', 'gender', 'heartrate']
  dropout: 0.5

optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  # name: cosine
  name: constant

epochs: 100
batch_size: 64