dataset:
  name: measured_mit_v1
  root: './data/measured_mit_v1/npy/'
  split_ratio: [0.625, 0.25, 0.125]
  custom_split_indices: [[0, 1, 2, 3, 4, 6, 7, 10, 12, 13, 14, 15, 17, 18, 19, 20, 21, 26, 27, 30, 31, 32, 33, 34, 36, 39, 40, 42, 43, 44, 45, 47, 48, 50, 51, 52, 53, 54, 55, 56, 59, 61],
    [5, 8, 11, 23, 25, 35, 37, 38, 41, 46, 49, 58, 60, 62, 63],
    [9, 16, 22, 24, 28, 29, 57]]
  beats_per_subject: 1
  resample_len: 100
  target: map
  part: 1

model:
  name: fc
  in_ch: 7
  out_ch: 512
  layer_num: 6
  feats: ['shape', 'v']

num_epochs: 2
batch_size: 64
workers_per_gpu: 8

criterion:
  name: mse

optimizer:
  name: adam
  lr: 1e-3
  weight_decay: 0.001

scheduler:
  name: constant

pdb: False

device: cpu